apiVersion: apps/v1
kind: Deployment
metadata:
  name: TO_BE_REPLACED
  namespace: TO_BE_REPLACED
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: gitweb-image
        imagePullPolicy: IfNotPresent