apiVersion: apps/v1
kind: Deployment
metadata:
  name: TO_BE_REPLACED
  namespace: TO_BE_REPLACED
  labels:
    app: TO_BE_REPLACED
    tilt-dev: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: TO_BE_REPLACED
  template:
    metadata:
      labels:
        app: TO_BE_REPLACED
    spec:
      containers:
      - name: TO_BE_REPLACED
        image: gitweb-image
        imagePullPolicy: IfNotPresent
        env:
        - name: "QUARKUS_LAUNCH_DEVMODE"
          value: "true"
        - name: "QUARKUS_PROFILE"
          value: "notdev"